"""Fix order shipping country code length

Revision ID: 096621fd25b0
Revises: 385e106f1959
Create Date: 2026-09-05 23:24:27.919814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096621fd25b0'
down_revision: Union[str, Sequence[str], None] = '385e106f1959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_country_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_country_code',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
