"""Add order reservation expiry

Revision ID: c1cca73c47ea
Revises: 096621fd25b0
Create Date: 2026-09-05 23:49:07.496603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cca73c47ea'
down_revision: Union[str, Sequence[str], None] = '096621fd25b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_reservation_expires_at'), 'orders', ['reservation_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_reservation_expires_at'), table_name='orders')
    op.drop_column('orders', 'reservation_expires_at')
    # ### end Alembic commands ###
